### ISSUE TITLE
Como posso contribuir de forma positiva nesse repositório?

### ISSUE THREAD

**Issue by ghost** [roneysco/Fake.br-Corpus#8]
Olá, tudo bem? como vão?

Como posso contribuir de forma positiva nesse repositório? existe alguma forma?

ps: acho esse projeto interessante e gostaria de ajudar.

**Comment by roneysco** [comment]
Olá! Tudo ótimo, e você?

Que legal! Fico muito feliz com sua ajuda!
Bom, o corpus está pronto. Se você propor outros atributos a partir do texto, para uso em algoritmos de aprendizado de máquina, seria interessante!

**Comment by ghost** [comment]
Oi @roneysco, como está?

> Olá! Tudo ótimo, e você?

Estou bem.

> Que legal! Fico muito feliz com sua ajuda!
> Bom, o corpus está pronto. Se você propor outros atributos a partir do texto, para uso em algoritmos de aprendizado de máquina, seria interessante!

valeu por esse comentário.
